travis:
  secure:
    BINSTAR_TOKEN: inIfoWc2uMGvwVLFOfNJAHPaRh+yYslsAHJ2JO9OhvKMIn2/YEj6sAhKmL+nmdYg2QUPLRHaqvkixJM8ftlUbp+xSmZYn5e9nNjEqtf6Asa8WL8H7IrJ8wX+kUziLMWfUap1Z9REVKoXQ4DeQS0Do+uC3tjOhTYXP7tHG0MhdH36QID77EebJTrE7gUlyqdqTgcoUd0fZZ4ospYvBe3QwNrkfVZK/eeeObtjfhsJoydEhjpLPvRnSdY1Yx/Md4QAffWYA4XzEy2Ferb9WnwD95rlzZeF6W5Z4/Pi6BuqL1SHKNODmHh5YWpsURSvXnLusBQVew48dUy/3sHmRzUiHYVxSpN0AE+HNToMDCZMVstDsbkanjc7SrIYFwHA9f0xpntSU8E9JK3dZ5aImgzF7ypj+05iyYEzq4ruwky0dKMYXE8XbQURP6fxV7A1DgMSJmzY7BD2hTBcfFwALPBdJiKPAHKyfFQF6g3iL/vD3U9bNnfn4iVVgCzco50K1yrHg8M318ykq8VjMkkSE7URWzLfRpqh89YQ5hMwkWChayXj3luCeePVjKOUWrtSDKRY3ZJPYoiV/vIBmpDVcgCV6VZPsovPFAe/aYIXd3/4pBFc4eVD/Ugj6B/g6kyn7DAslNlSpL8zGNZyXJjSEFJF/09u1wx/ofNrmi9+Y3OQ+8Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
